import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ui/toast";
import QueryClientProviderWrapper from "@/providers/query-client-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Adrify - Système d'adressage en ligne",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="fovicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <QueryClientProviderWrapper>
          <ToastProvider>{children}</ToastProvider>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
